### PR TITLE
Update ApkPathUtils.java

### PR DESCRIPTION
**Pull request by adrianp-sti**
Fix for package names with period in the main part of the name

(brief, plain english overview of your changes here)

This pull request makes the following changes:
* (your change here)
* (another change here)
* (etc)

(If there are changes to the UI, please include a screenshot so we
know what to look for!)

(If there are changes to user behavior in general, please make sure to
update the docs, as well)

It relates to the following issue #s:
* Fixes #X

cc @DarthHater @bhamail

### CODE REVIEW

**Comment by DarthHater** [comment]
@adrianp-sti couple tiny observations:

- This could use a new unit test
- If we really want to make sure it works, we could add an integration test too

I think @allenhsieh will be popping in here, he might be able to help you out if you'd like!

**Comment by bhamail** [comment]
More deets in Issue #4

**Comment by allenhsieh** [comment]
Hi @adrianp-sti, I can help with getting some unit/integration tests up today. Was there a specific package that was causing you issues that I can test against?

**Comment by adrianp-sti** [comment]
Hi Allen,

Thanks for the offer of help. Specifically it was lua5.3-libs-5.3.5-r2.apk
that was causing the issue.  To be honest I think it'll be any package that
has a period in the main part of the package name but the Lua one was the
first example I came across.  I ended up just writing a small test based on
the name() method in ApkPathUtils.java to see if the fix worked and didn't
adversely affect the parsing of any other APK names.

adrian.

**Comment by allenhsieh** [comment]
Hey @adrianp-sti thanks for your reply! I deleted my initial comment because it was graciously pointed out to me that @bhamail linked to the issue, and the issue named the package in question.

I forked off your fork and just finish writing some unit and integration tests, it should be good to squash and merge: https://github.com/adrianp-sti/nexus-repository-apk/pull/1

**Comment by adrianp-sti** [comment]
I've found a few more use cases which I'll comment on in #4 so until there's a fix for all the new issues I'll close this and submit a new pull-up when ready.

**Pull request closed without merging**
