### PR TITLE
Update package version regex

### PR DESCRIPTION
**Pull request by sjweixel**
Update apk package version number regex to include letters and underscore so it works on with files like lua-socket-3.0_rc1_git20160306-r2.apk and ncurses-libs-6.1_p20200118-r4.apk

Update regex to work with apk package filenames in public Alpine repo that don't have the format X.X.X-rX ,

This pull request makes the following changes:

added a new regexp expression to be used in version() and name()
cc @DarthHater @bhamail

### CODE REVIEW

**Comment by sjweixel** [comment]
Please review.

**Review by bhamail — APPROVED** [review]
LGTM, +1

**Comment by bhamail** [comment]
Would it be worth adding a (or altering an existing) unit test to show and example of the case this change is meant to cover?
Up to you.

**Review by bhamail — APPROVED** [review]
+1, Thanks!

**Pull request merged**
